const express = require('express');
const app = express();
const PORT = 7000;
const artScreenData = [
  { 'url': 'https://i.postimg.cc/FzbcnNWF/alex-perez-p-Egs-WN0kwb-Q-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/K88LJXnF/and-machines-vq-TWfa4-Dj-Ek-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/9fPxZHV2/brandi-redd-a-JTi-W00qqt-I-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/762S0gS2/bryan-garces-IXUM4c-Jyn-P0-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/q7HbNMPQ/bryan-garces-LMi-Xu-Fec-r-Y-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/Yq3Y62Lb/bryan-garces-N0-JDg-KOLLh-U-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/KzBmnzjz/camille-couvez-H5-Pn-IYI-1-I0-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/mkppk34F/daniel-olah-1n-UNsm-Wfc-Sk-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/SN5tpGVB/david-pisnoy-46ju-D4z-Y1-XA-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/6QbngBrt/felix-dubois-robert-Cu-Evr-Pd3-NYc-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/5NPz6xrv/guy-stevens-d-EGu-o-Cu-B1-Y-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/BQvsQsDd/heather-ford-Fq54-Fqucg-CE-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/9fNvrjBf/ian-dooley-TLD6i-COlyb0-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/y8YJHwYd/jason-leung-w-Hdd-Vi-Tm-Sv-A-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/vBW89zHk/joel-filipe-Mbf3x-Fi-C1-Zo-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/vmT6WCpj/liam-martens-z-QSy-HYvyh-o-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/htjGwTpQ/markus-spiske-k0r-Vud-Bo-B4c-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/v89ZFPQn/maxim-berg-lnvpji4f-C3c-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/CL6ZwcZs/meric-dagli-3-KJp-F86n-R4c-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/t45M1Vjk/milad-fakurian-7-Wjmy3m6-Nlo-unsplash-1.jpg' },
  { 'url': 'https://i.postimg.cc/1R8XJp7g/paulina-milde-jachowska-W7p-T-Z-VMUQ-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/g2CnZrHw/pawel-czerwinski-8u-ZPyn-Iu-r-Q-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/4xg3fjft/pawel-czerwinski-TZLz-BWQ8-Hnc-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/T1zZ987c/pexels-alexander-ant-4585185.jpg' },
  { 'url': 'https://i.postimg.cc/43XRqgJL/pexels-alexander-grey-1149019.jpg' },
  { 'url': 'https://i.postimg.cc/6pJXVZFN/pexels-alexander-grey-1428169.jpg' },
  { 'url': 'https://i.postimg.cc/hP7n7syr/pexels-deeana-arts-1646953.jpg' },
  { 'url': 'https://i.postimg.cc/KjPdJq6S/pexels-eberhard-grossgasteiger-2086361.jpg' },
  { 'url': 'https://i.postimg.cc/NjDQgMPq/pexels-lumn-587958.jpg' },
  { 'url': 'https://i.postimg.cc/RZLZNGhY/pexels-ravi-kant-1927595.jpg' },
  { 'url': 'https://i.postimg.cc/Fz5Mb5nV/pexels-steve-johnson-1585325.jpg' },
  { 'url': 'https://i.postimg.cc/0QgWFGd8/pexels-steve-johnson-1690351.jpg' },
  { 'url': 'https://i.postimg.cc/ZRr7S9V6/pexels-torsten-dettlaff-971546.jpg' },
  { 'url': 'https://i.postimg.cc/V6pY3VZJ/swati-b-FP3z-YIe-Dql-M-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/x1fSFQjs/tengyart-y-KNWXUx6d-Y-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/j5wTQhqt/tevei-renvoye-o-Tlk-BFUU0p8-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/VkVHBPJ0/trnava-university-511nue4-Yd7o-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/sf5djxv6/victor-grabarczyk-w-N9-DU73b8-s-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/0N3RQJY3/visax-6rpim0-I8edo-unsplash.jpg' },

]
const architectureScreenData = [
  { 'url': 'https://i.postimg.cc/YrFgvNNz/anthony-delanoix-o0pifdpv-J-o-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/HW2rM6rX/anthony-reungere-s6xt1mw-F-i-U-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/L8PQCgKk/bobby-stevenson-FHdhi8q-Q1i-U-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/Zn9xWXJP/brayden-law-L9ac-Hll14-K8-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/R0Qs9r0N/chuttersnap-1mm-ZEQJLv0k-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/kgwshQYb/colin-lloyd-H-j0-S6-Gu8-Jk-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/nhVY7sVc/damiano-baschiera-Ktl-Bp-Yttl-Y-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/3xwmNP9k/dawson-lovell-W-MUqtu-Hwy-Y-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/J7fRGJqZ/erik-eastman-4-HG5hlhm-Zg8-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/02yb07S3/francesca-saraco-f-C9ydjo-OOHA-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/yxbBP344/frank-okay-J76-Crc-KWG5c-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/6psxpXB0/gerald-dicen-f-KLBPt-G9ob-I-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/MT0vdDdk/hyundai-motor-group-csa-Gc-WO9bu0-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/7YJbRwBM/ilnur-kalimullin-CB0-Qrf8ib4-I-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/yYf40ZhL/jake-blucker-t-Mz-Cr-Bk-M99-Y-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/s24JZp7X/jc-gellidon-Khqmo4-T-rs0-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/gjgc7cQd/john-rodenn-castillo-Xz-UAEc-Z7d-Dg-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/wvK15v8G/josh-couch-y-EHQf-GNKn-Z4-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/QCPT9qbR/joshua-newton-Njbs-Ekkv-Owc-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/fycmSdVC/karsten-wurth-u-Zt8w-D1rgeo-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/438gZ2wb/karthik-chandran-4e0-Pvf-HCln-I-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/4dT37SpC/lerone-pieters-5d-JM5-Bkgn78-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/fRJy6XMP/marialaura-gionfriddo-m-Z8-TPyc-Wm-Ho-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/C1Hxjs4R/mark-asthoff-D6-JT1-MCWOds-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/500FNGJx/mateusz-klein-Lk-PFNXv-LS44-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/SRqgJkgB/nathan-dumlao-1qsbpl-LDUa8-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/DZMnQpXy/nathana-reboucas-FRyu9-OIk-YXU-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/4xXJv9SM/nikolay-vorobyev-d9he-OQ-r-Kz-I-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/2y1vTt9H/olivia-hutcherson-LUWyya-Hsz-AU-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/9z34bQ7M/pawel-nolbert-4u2-U8-EO9-Oz-Y-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/cL1StNKG/pexels-alex-azabache-3214995.jpg' },
  { 'url': 'https://i.postimg.cc/gjGMtGbY/sawyer-bengtson-zisn-Y9g-Wr3-Y-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/0NDRL5Fm/shot-by-cerqueira-IJmr4nrqzow-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/fbxjG1Kk/thanos-pal-Vm-Fbd-QNHeo-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/m2H1DJcw/thomas-chan-C-xhy-Au-OSA-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/KzgP7zqK/tom-barrett-ui-Kq-Lsjus-B0-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/SRdfRP1V/Untitled-design-2.png' },
  { 'url': 'https://i.postimg.cc/fT9G3RWP/yashika-chhabaria-x-Ndfkwm-QFno-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/gjtGYzpD/yeshi-kangrang-w-TD1-u8x1g-unsplash.jpg' },

];
const blackScreenData = [
  { 'url': 'https://i.postimg.cc/0jfjwf2Z/aaron-huber-V09-Io5ln-Qo-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/KYHnKms4/adam-birkett-Ir-FSypwykg-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/2ycmYX5p/adrien-olichon-GH9-Lwhl-SO4-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/sXb9L3pb/akira-hojo-p-LJ97-CLu-Yc-U-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/ZYyLdymm/alexandru-acea-q-EXFE5h0e8g-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/mrYskrry/andrik-langfield-xbne-Mn4-Rzko-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/0QK7DhLn/annie-spratt-XU6-Ys-Obq-Dbo-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/13y02CqR/ave-calvar-ltu-Lbi-Q1h-M-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/9XtrKWtT/daniel-lincoln-xm49-F658-Ry-M-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/ZqR8KWH1/david-werbrouck-Rf-Xv1sna-YEI-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/5N46MZnr/guillaume-coupy-KZpc-NDt-Fsvw-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/hjRtZwXp/haniel-cal-f-Khcm4i-Ao-FA-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/HLHNS9pb/jeremy-bishop-rq-Wo-B4-LFgmc-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/QxfVN0zd/jonathan-kemper-0-F4c-VA5p9w0-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/4dvND5tZ/joshua-rivera-usmh-Pm-T5sj0-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/Ss4mfMPP/klim-musalimov-F7x-Rd-XXvx9c-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/L5bdwYy2/klim-musalimov-jg5o-Ke-dz0-E-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/13NPxBhT/max-kleinen-Ghrq-Mk-A4c-VA-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/d37N7WBc/nick-jones-v-HIa-Tqzewq0-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/BZYGXkJk/nick-nice-g-Pm8h3-DS1s4-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/K87qg3nj/patrick-tomasso-D6-Bk1-A3-g-MA-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/JnKC3dZy/pexels-4151043.jpg' },
  { 'url': 'https://i.postimg.cc/25fssfxb/pexels-anubhaw-anand-2027697.jpg' },
  { 'url': 'https://i.postimg.cc/XYFM1v96/pexels-bestbe-models-2249741.jpg' },
  { 'url': 'https://i.postimg.cc/435SjHdq/pexels-churckyno-bryant-1546035.jpg' },
  { 'url': 'https://i.postimg.cc/V6kVws06/pexels-derice-jason-fahnkow-1595244.jpg' },
  { 'url': 'https://i.postimg.cc/XqTH9wHG/pexels-marek-kupiec-3974516.jpg' },
  { 'url': 'https://i.postimg.cc/cLmqGbkF/pexels-mohamed-abdelsadig-3356833.jpg' },
  { 'url': 'https://i.postimg.cc/HkP2M0rp/pexels-pixabay-276092.jpg' },
  { 'url': 'https://i.postimg.cc/cHk5Lqfc/pexels-pixabay-67823.jpg' },
  { 'url': 'https://i.postimg.cc/7LdmF14B/pexels-swapnil-sharma-1837168.jpg' },
  { 'url': 'https://i.postimg.cc/ZK4Vz5kh/pexels-thirdman-5981927.jpg' },
  { 'url': 'https://i.postimg.cc/xT5gfVYN/pexels-thirdman-5981928.jpg' },
  { 'url': 'https://i.postimg.cc/DZ4Y0j5k/pexels-warren-bradley-3212378.jpg' },
  { 'url': 'https://i.postimg.cc/HkSS2Dh1/pexels-yigithan-bal-765062.jpg' },
  { 'url': 'https://i.postimg.cc/KztrCdJz/polina-silivanova-dqe-Mw-YW9f-CY-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/8PmX7rd5/quinton-coetzee-u-n1-AFj-Uclo-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/Bnvpt7QY/ryunosuke-kikuno-v7xw4p7-Kd-FQ-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/J0cxH9kg/salman-khan-Iksnc-Vbq6ss-unsplash.jpg' },

]
const cityscapeScreenData = [
  { 'url': 'https://i.postimg.cc/wxrVGQ6n/8e7d95d3fdbd48ac9bb83c6ffc654e9c.png' },
  { 'url': 'https://i.postimg.cc/xqrLTg8C/Isbah-hounted-house-in-a-urban-city-e2146401-f733-4099-9b5c-387086d0f66a-1.png' },
  { 'url': 'https://i.postimg.cc/jjjc1g70/Isbah-hyper-car-on-modern-street-at-night-a8735af1-94d9-4d31-8843-cae45b250e69-1-1.png' },
  { 'url': 'https://i.postimg.cc/k57FbjcR/mika-korhonen-m-IXhh8-If-Xqg-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/DwRmVmWv/pexels-aleksandar-pasaric-2385210.jpg' },
  { 'url': 'https://i.postimg.cc/664jwm1B/pexels-anas-hinde-2906882.jpg' },
  { 'url': 'https://i.postimg.cc/Dzqvt6k6/pexels-andrew-neel-3178798.jpg' },
  { 'url': 'https://i.postimg.cc/rwMQ1Fyp/pexels-arthur-brognoli-2260786.jpg' },
  { 'url': 'https://i.postimg.cc/MpLfWdL8/pexels-brayden-law-1738994.jpg' },
  { 'url': 'https://i.postimg.cc/P5CNF15V/pexels-cameron-casey-1334607.jpg' },
  { 'url': 'https://i.postimg.cc/FR7PYWrg/pexels-duophenom-2414918.jpg' },
  { 'url': 'https://i.postimg.cc/FsBHc1Vy/pexels-erik-mclean-5214413.jpg' },
  { 'url': 'https://i.postimg.cc/cHyK36Z9/pexels-furknsaglam-3109671.jpg' },
  { 'url': 'https://i.postimg.cc/jjN2RKNz/pexels-guillermo-arroyo-2225759.jpg' },
  { 'url': 'https://i.postimg.cc/W1qb7j5Q/pexels-ian-beckley-2440013.jpg' },
  { 'url': 'https://i.postimg.cc/Lsd4C77h/pexels-irina-iriser-1707215.jpg' },
  { 'url': 'https://i.postimg.cc/L502z0L9/pexels-josh-hild-3773297.jpg' },
  { 'url': 'https://i.postimg.cc/xTc00nVc/pexels-josh-hild-3859774.jpg' },
  { 'url': 'https://i.postimg.cc/QxwjCwjS/pexels-julia-volk-5656765.jpg' },
  { 'url': 'https://i.postimg.cc/Qx9r2mc7/pexels-kaique-rocha-108153.jpg' },
  { 'url': 'https://i.postimg.cc/QNn3YwKs/pexels-karl-solano-2739277.jpg' },
  { 'url': 'https://i.postimg.cc/T3VBx41K/pexels-karl-solano-2884590.jpg' },
  { 'url': 'https://i.postimg.cc/L6cM2PVb/pexels-kehn-hermano-3849167.jpg' },
  { 'url': 'https://i.postimg.cc/dVPgzYsM/pexels-kehn-hermano-3849168.jpg' },
  { 'url': 'https://i.postimg.cc/4yMRKHRn/pexels-lukas-rodriguez-3680219.jpg' },
  { 'url': 'https://i.postimg.cc/MHX8Kb4h/pexels-mark-dalton-1528348.jpg' },
  { 'url': 'https://i.postimg.cc/8cxxk8L6/pexels-misael-garcia-1707820.jpg' },
  { 'url': 'https://i.postimg.cc/wxtqz9p3/pexels-mohamed-almari-1454253.jpg' },
  { 'url': 'https://i.postimg.cc/054T0Shy/pexels-oziel-g-mez-1755385.jpg' },
  { 'url': 'https://i.postimg.cc/kgy9s4xY/pexels-paul-basel-1816714.jpg' },
  { 'url': 'https://i.postimg.cc/mZ0b2KLj/pexels-piccinng-3052361.jpg' },
  { 'url': 'https://i.postimg.cc/vBBKW8zn/pexels-pixabay-162031.jpg' },
  { 'url': 'https://i.postimg.cc/dtrJ7nDY/pexels-sergio-souza-3640993.jpg' },
  { 'url': 'https://i.postimg.cc/vT9wVHYz/pexels-vitor-gusm-o-shimabukuro-2104044.jpg' },
  { 'url': 'https://i.postimg.cc/4xGspthh/pexels-well-naves-1829067.jpg' },
  { 'url': 'https://i.postimg.cc/8CKG80Xh/pexels-zeeshaan-shabbir-11511728.jpg' },
  { 'url': 'https://i.postimg.cc/3RkT3Fzz/Untitled-design.png' },
  { 'url': 'https://i.postimg.cc/vBCdT6sT/Untitled-design-2.png' },
  { 'url': 'https://i.postimg.cc/QxwjCwjS/pexels-julia-volk-5656765.jpg' },
]
const mountainScreenData = [
  { 'url': 'https://i.postimg.cc/ryS4Rtsv/alessio-soggetti-8je-We-Kdygfk-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/Kj45xGrZ/alessio-soggetti-cf-KC0-UOZHJo-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/QxH6rb0p/cody-scott-milewski-3j4-AG5-VQVs-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/43L5MHV8/cristhian-carreno-xw-CB46wsic-A-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/nhZfVg5y/dani-garcia-f-JQam-CZIZf8-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/KzC5cX9B/evan-wise-4-ZEn-Dflc-JQ0-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/BQ9dNRqj/fabrizio-conti-i96-EPuuuz-So-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/8kJSZhM0/fabrizio-conti-K94-Hi-VOKj-ZE-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/9XpMjPrF/fabrizio-conti-UBiz-WTA9-q-A-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/8kK76BDX/Isbah2004-Boat-in-front-of-mountain-Purple-theme-2df56b9f-8b8d-40ae-9167-806744d300d0.png' },
  { 'url': 'https://i.postimg.cc/1Xj41PJ1/Isbah2004-lightening-on-a-mountain-b9eed718-3bb7-4e25-aaac-a60b7be69c43.png' },
  { 'url': 'https://i.postimg.cc/Hng1JNn8/Isbah2004-man-wearing-red-jacket-walks-in-front-of-mountain-0ecc701a-74a5-435d-939d-7fc45f9c2510.png' },
  { 'url': 'https://i.postimg.cc/NMTKTL8J/Isbah2004-mountain-covered-with-grass-66b4a2ee-79fc-45a2-b6f8-a01ee8b9697e.png' },
  { 'url': 'https://i.postimg.cc/7ZxSk11x/Isbah2004-mountain-exploding-infront-of-sun-realistic-1255c1b5-5e3e-4b05-99d9-e3c1b5cce030.png' },
  { 'url': 'https://i.postimg.cc/6Q82WM8N/Isbah2004-mountain-in-front-of-river-3e5f978e-ac18-4141-b27b-bf9064c9d616.png' },
  { 'url': 'https://i.postimg.cc/4yfhgstW/Isbah2004-mountain-ranges-view-from-road-5ff6233f-4c15-4c93-b094-afd5684a85d5.png' },
  { 'url': 'https://i.postimg.cc/V61Jqm7z/Isbah2004-peak-of-the-mountain-covered-with-cloud-a50dbc70-57fa-4aa1-a936-0bbb15f4d0f3.png' },
  { 'url': 'https://i.postimg.cc/v804nR5d/Isbah2004-train-running-on-railway-track-in-between-mountain-ra-c5abc781-dcaf-4e73-b4e7-036572bd6d80.png' },
  { 'url': 'https://i.postimg.cc/qqSBZwvk/Isbah-mountains-colliding-0740d8fe-9a74-461a-a596-de9b2794d8ae.png' },
  { 'url': 'https://i.postimg.cc/ydKZLVrf/Isbah-mountain-next-to-jupiter-a1d8a9b2-8b6b-4df4-88ec-f65edff3f176.png' },
  { 'url': 'https://i.postimg.cc/VkWQSwbq/john-rodenn-castillo-eluz-JSfk-NCk-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/GpyfkjZF/jon-r8-AFUp-Rp0-J0-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/yYWkXfT3/kateryna-i-wpz5z-Xj9li-E-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/T1KfmsXR/kldjkdl.png' },
  { 'url': 'https://i.postimg.cc/tCLCd9T8/pexels-ali-kazal-13608345.jpg' },
  { 'url': 'https://i.postimg.cc/SsDxc82G/pexels-chris-czermak-2444429.jpg' },
  { 'url': 'https://i.postimg.cc/wMRY3shM/pexels-clive-kim-4220967.jpg' },
  { 'url': 'https://i.postimg.cc/FRBQ9xkw/pexels-eberhard-grossgasteiger-1624496.jpg' },
  { 'url': 'https://i.postimg.cc/vDRTmy6R/pexels-eberhard-grossgasteiger-1699025.jpg' },
  { 'url': 'https://i.postimg.cc/y6h8mM9N/pexels-eberhard-grossgasteiger-2086621.jpg' },
  { 'url': 'https://i.postimg.cc/k4KKFTFd/pexels-eberhard-grossgasteiger-2088170.jpg' },
  { 'url': 'https://i.postimg.cc/qqffWv33/pexels-gianluca-grisenti-4215113.jpg' },
  { 'url': 'https://i.postimg.cc/HsRWdT1B/pexels-michael-block-3225530.jpg' },
  { 'url': 'https://i.postimg.cc/pXx4j7YR/pexels-philip-ackermann-1666021.jpg' },
  { 'url': 'https://i.postimg.cc/qvNL6XYp/pexels-pixabay-163992.jpg' },
  { 'url': 'https://i.postimg.cc/bwygYf0S/pexels-rok-romih-3312569.jpg' },
  { 'url': 'https://i.postimg.cc/FsS9Gwwq/pexels-sebastian-palomino-1955134.jpg' },
  { 'url': 'https://i.postimg.cc/4ySQdYX8/roland-losslein-Dm-DYX-lt-I48-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/3J1r6zKx/Untitled-design-1-1.png' },
]
const patternScreenData = [
  { 'url': 'https://i.postimg.cc/Bbm975sh/8machine-XM8tkt-DM1-X4-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/KjfxSS7D/abstract-image-of-colored-paper-in-triangular-shapes.jpg' },
  { 'url': 'https://i.postimg.cc/fW2rFRmg/alex-zahn-tn-D-L-Mxa-P8-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/CLvSc0xF/anunay-rai-BV6gu64-ZEj8-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/x8nn4Tmd/anunay-rai-OQOXKv-TKNco-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/76My08Rr/barbaliu-alexandra-ntk-F4-I2a18-E-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/gcsW0pRv/Isbah-golden-geometric-patterns-2db0a357-1e30-4ceb-a462-259e5f386bf6.png' },
  { 'url': 'https://i.postimg.cc/kMvntKrR/joel-filipe-Wc8k-Kry-EPM-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/bJjhZN3R/kate-bezzubets-wxg-O5b-LN2-Co-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/Yq2tN0kn/magicpattern-am-yg8w-LLIo-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/k4ykDNVn/max-williams-Oo-K2-W7-OPRM-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/G2RWcgm7/pexels-adrien-olichon-2387798.jpg' },
  { 'url': 'https://i.postimg.cc/0jk1CXgM/pexels-adrien-olichon-3137055.jpg' },
  { 'url': 'https://i.postimg.cc/tCmGhzBJ/pexels-akshar-dave-3290477.jpg' },
  { 'url': 'https://i.postimg.cc/8cK9m1B9/pexels-anna-tarazevich-6486624.jpg' },
  { 'url': 'https://i.postimg.cc/158jZ1KR/pexels-athena-1567356-1.jpg' },
  { 'url': 'https://i.postimg.cc/VkLBcqwq/pexels-benjamin-suter-3617454.jpg' },
  { 'url': 'https://i.postimg.cc/xd2xHJVq/pexels-brett-sayles-2881221.jpg' },
  { 'url': 'https://i.postimg.cc/CxymTB1J/pexels-brett-sayles-3653997.jpg' },
  { 'url': 'https://i.postimg.cc/Wz3f3BLn/pexels-engin-akyurt-1493226.jpg' },
  { 'url': 'https://i.postimg.cc/s2smxk5h/pexels-laura-james-6102523.jpg' },
  { 'url': 'https://i.postimg.cc/rpwhQ6zL/pexels-mathias-reding-8368984.jpg' },
  { 'url': 'https://i.postimg.cc/W3JxwRf1/pexels-mitchell-luo-3685175.jpg' },
  { 'url': 'https://i.postimg.cc/MZF95rJC/pexels-mithul-varshan-3023211.jpg' },
  { 'url': 'https://i.postimg.cc/d0G824jK/pexels-pixabay-534247.jpg' },
  { 'url': 'https://i.postimg.cc/3N4V1sSw/pexels-schub-rt-schneider-13051506.jpg' },
  { 'url': 'https://i.postimg.cc/1R7J57WW/pexels-scott-webb-305816.jpg' },
  { 'url': 'https://i.postimg.cc/KY0W2GCz/pexels-scott-webb-593159.jpg' },
  { 'url': 'https://i.postimg.cc/y628Kszv/pexels-silvia-trigo-3173587.jpg' },
  { 'url': 'https://i.postimg.cc/G2JV5PrW/pexels-vlado-paunovic-3112019.jpg' },
  { 'url': 'https://i.postimg.cc/HLKvvSfv/pexels-yelena-odintsova-10559026.jpg' },
  { 'url': 'https://i.postimg.cc/YqqNg6Pv/photoholgic-zt-EZJ8-FBr8o-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/QxMwfWzz/pierre-chatel-innocenti-70-Rls5-I1wo-M-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/zvhjQ8nV/roberto-reposo-Ieac9-Zi47-s-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/DzYRkfbg/shambhavi-singh-o1mknm-m-Sg-A-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/kgHmQyXw/shubham-dhage-Nn-XAJPo3bb0-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/qB906wqL/simone-hutsch-Xfodt-Zo-Vh-U-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/QCSpwCFN/yarovoe7-sliver-metalic-geometric-patterns-5c3c25a2-8b3e-468f-86b0-9fb771ea26e4-1.png' },
  { 'url': 'https://i.postimg.cc/G2RWcgm7/pexels-adrien-olichon-2387798.jpg' },
]
const skyScreenData = [
  { 'url': 'https://i.postimg.cc/kGbXkh1j/aboodi-vesakaran-f-FSLQPn-Zz-KE-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/FKrgbwDX/aldebaran-s-z-Am8-YFp-CCsc-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/8CZ5Wvfb/alexander-andrews-y-OIT88x-Wkbg-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/jCYdKQBR/chen-liu-jgt81f-UDu-U-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/50GBVy1f/cristofer-maximilian-JLYt-IEA9d-o-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/FsSZhy78/daniel-monteiro-zyyb-Gj5v-m-A-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/Z5VymnFX/daniel-olah-HNkg-PFBSh-Sw-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/zDbwkCSv/danny-lines-dwjfdde-DBZs-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/NMVjCw49/edvin-karlsson-yf-CLVvjg-Mm-Q-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/kgntLK8x/ferenc-horvath-skc-Fi-Bu91-AA-unsplash-1.jpg' },
  { 'url': 'https://i.postimg.cc/SNcWBmPp/gino-0g-Tt-Es-OBJDo-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/j27zdTdP/ian-parker-r-Wey-wse-Ec-Y-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/tCdxr21q/jasper-wilde-GQSNmxmlgn-Q-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/qBwrjKJf/jeremy-thomas-k-Fy1-Aip0e-Eo-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/FR2L66gR/jordon-conner-VIc-Tzkz-NZR8-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/mkCHWS8S/manjunath-h-p-a-O0ro53-Yg-M-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/sDJMPx81/matt-gross-u-Pa8m-Fby-SYw-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/MH7vFppP/navi-68f0-XMXRHkc-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/MH2n5Qqf/pawel-czerwinski-f-Ad4u-HTGGY-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/pVzhTqJf/pexels-adi-k-3222255.jpg' },
  { 'url': 'https://i.postimg.cc/Nj3v574X/pexels-alex-andrews-816608.jpg' },
  { 'url': 'https://i.postimg.cc/ZRJgdfyW/pexels-attilio-grassi-14131115.jpg' },
  { 'url': 'https://i.postimg.cc/B6xSqwft/pexels-eberhard-grossgasteiger-1624360.jpg' },
  { 'url': 'https://i.postimg.cc/FKkF6HPy/pexels-eberhard-grossgasteiger-2098427.jpg' },
  { 'url': 'https://i.postimg.cc/tCgjfgJs/pexels-egil-sj-holt-1906658.jpg' },
  { 'url': 'https://i.postimg.cc/Pf3cCQfq/pexels-hristo-fidanov-1252871.jpg' },
  { 'url': 'https://i.postimg.cc/JhS07kyY/pexels-kush-kaushik-2078126.jpg' },
  { 'url': 'https://i.postimg.cc/sgZtdGrg/pexels-marco-milanesi-2670898.jpg' },
  { 'url': 'https://i.postimg.cc/4dbGC7p9/pexels-rakicevic-nenad-1274260.jpg' },
  { 'url': 'https://i.postimg.cc/Dy096Yps/pexels-sam-kolder-2387877.jpg' },
  { 'url': 'https://i.postimg.cc/BbKVWRrw/pexels-sam-willis-3934512.jpg' },
  { 'url': 'https://i.postimg.cc/VN8Zx7gK/pexels-stanislav-kondratiev-2908971.jpg' },
  { 'url': 'https://i.postimg.cc/s2dbVfj9/pexels-stanislav-kondratiev-2909261.jpg' },
  { 'url': 'https://i.postimg.cc/mZzqFFPN/pexels-tomas-anunziata-412026.jpg' },
  { 'url': 'https://i.postimg.cc/CLbQcTHR/pexels-yasin-g-ndogdu-2644734.jpg' },
  { 'url': 'https://i.postimg.cc/LXyyZmpW/solen-feyissa-54xm-XW7t-Jzo-unsplash.jpg' },
  { 'url': 'https://i.postimg.cc/MG94170t/Untitled-design.png' },
  { 'url': 'https://i.postimg.cc/d0sp7HCL/Untitled-design-1.png' },
  { 'url': 'https://i.postimg.cc/N0kCB1PB/zoltan-tasi-HQPJEEj-Hq-SE-unsplash.jpg' },
]
const colorsScreenData = [
  { 'url': 'https://i.postimg.cc/W1dPPnrr/Untitled-design.png' },
  { 'url': 'https://i.postimg.cc/GpS8mzSC/Untitled-design-1.png' },
  { 'url': 'https://i.postimg.cc/6pMTMYKv/Untitled-design-10.png' },
  { 'url': 'https://i.postimg.cc/7Lbhd0PQ/Untitled-design-11.png' },
  { 'url': 'https://i.postimg.cc/3w6NTNdr/Untitled-design-12.png' },
  { 'url': 'https://i.postimg.cc/63v35Kvr/Untitled-design-13.png' },
  { 'url': 'https://i.postimg.cc/BbfvjzTd/Untitled-design-14.png' },
  { 'url': 'https://i.postimg.cc/mk3gCSVh/Untitled-design-15.png' },
  { 'url': 'https://i.postimg.cc/BZ26rqss/Untitled-design-16.png' },
  { 'url': 'https://i.postimg.cc/sDyXytDW/Untitled-design-17.png' },
  { 'url': 'https://i.postimg.cc/28w552VK/Untitled-design-18.png' },
  { 'url': 'https://i.postimg.cc/x111NMmT/Untitled-design-19.png' },
  { 'url': 'https://i.postimg.cc/L6Mq5Jvn/Untitled-design-2.png' },
  { 'url': 'https://i.postimg.cc/SKXQD4VB/Untitled-design-20.png' },
  { 'url': 'https://i.postimg.cc/sgHDYxPP/Untitled-design-21.png' },
  { 'url': 'https://i.postimg.cc/rpvVHHPK/Untitled-design-22.png' },
  { 'url': 'https://i.postimg.cc/FR3rXxMG/Untitled-design-23.png' },
  { 'url': 'https://i.postimg.cc/j2Tsx7KT/Untitled-design-24.png' },
  { 'url': 'https://i.postimg.cc/3NZ3dxJv/Untitled-design-25.png' },
  { 'url': 'https://i.postimg.cc/8kdpytBz/Untitled-design-26.png' },
  { 'url': 'https://i.postimg.cc/NfggZmp7/Untitled-design-27.png' },
  { 'url': 'https://i.postimg.cc/9FJW20k3/Untitled-design-28.png' },
  { 'url': 'https://i.postimg.cc/7ZhqZDv5/Untitled-design-29.png' },
  { 'url': 'https://i.postimg.cc/wxNy9XXC/Untitled-design-3.png' },
  { 'url': 'https://i.postimg.cc/jS1tW9KZ/Untitled-design-30.png' },
  { 'url': 'https://i.postimg.cc/mrFR7wgR/Untitled-design-31.png' },
  { 'url': 'https://i.postimg.cc/brqhcfHN/Untitled-design-32.png' },
  { 'url': 'https://i.postimg.cc/0QRvnwzS/Untitled-design-33.png' },
  { 'url': 'https://i.postimg.cc/FRy4BHSB/Untitled-design-34.png' },
  { 'url': 'https://i.postimg.cc/vTXdG237/Untitled-design-35.png' },
  { 'url': 'https://i.postimg.cc/tRzbd7p1/Untitled-design-36.png' },
  { 'url': 'https://i.postimg.cc/c44SFZLF/Untitled-design-37.png' },
  { 'url': 'https://i.postimg.cc/3JSH66yY/Untitled-design-39.png' },
  { 'url': 'https://i.postimg.cc/sXQBQStZ/Untitled-design-6.png' },
  { 'url': 'https://i.postimg.cc/sgmGt3Y1/Untitled-design-7.png' },
  { 'url': 'https://i.postimg.cc/yNN3K2jj/Untitled-design-8.png' },
  { 'url': 'https://i.postimg.cc/Qd8Hgv2D/Untitled-design-9.png' },
  { 'url': 'https://i.postimg.cc/mZjgNYwt/Untitled-design.png' },
  { 'url': 'https://i.postimg.cc/VvZ1yFGg/Untitled-design-1.png' },
  
]
const texturesScreenData = [
  {'url':'https://i.postimg.cc/YCPbmc9n/aaron-burden-6-DD9-FJYj0-Vo-unsplash.jpg'},
  {'url':'https://i.postimg.cc/5NnPbQMM/abhishek-tiwari-qb-EDj-Tz-N2b-E-unsplash.jpg'},
  {'url':'https://i.postimg.cc/cJ8TRDts/aedrian-u8-VXlq-Qt5-GI-unsplash.jpg'},
  {'url':'https://i.postimg.cc/7ZKjsQL0/alexander-grey-Wq-PAETBU2-G8-unsplash.jpg'},
  {'url':'https://i.postimg.cc/9XDrXv9g/andrii-leonov-WXdef-C-imv-U-unsplash.jpg'},
  {'url':'https://i.postimg.cc/qvq1RBk6/annie-spratt-MA6110-CNn-Dk-unsplash.jpg'},
  {'url':'https://i.postimg.cc/K8WmWYqZ/daniele-levis-pelusi-mk-MSXR86k-YY-unsplash.jpg'},
  {'url':'https://i.postimg.cc/NjjzH7xM/dylann-hendricks-37-XNY0jy12-U-unsplash.jpg'},
  {'url':'https://i.postimg.cc/NMqDp1RR/fly-d-9u7oc9cv-V0s-unsplash.jpg'},
  {'url':'https://i.postimg.cc/cCJnmHkQ/gabriella-clare-marino-CFt-CXs-UTLS4-unsplash.jpg'},
  {'url':'https://i.postimg.cc/76WfDyN4/jocelyn-morales-GWVb-NJU8h-OM-unsplash.jpg'},
  {'url':'https://i.postimg.cc/3R1Gmp18/joel-naren-V8p9ql6-w-Go-unsplash.jpg'},
  {'url':'https://i.postimg.cc/QCNpySCK/jonas-denil-MQOh-Qh-F8-WN0-unsplash.jpg'},
  {'url':'https://i.postimg.cc/5twL9DFF/marek-slomkowski-4-R65-LZQXf5-I-unsplash.jpg'},
  {'url':'https://i.postimg.cc/d1wdhn8N/martin-woortman-Nld6b6algms-unsplash.jpg'},
  {'url':'https://i.postimg.cc/RVVRsCJp/nick-nice-zwj-SCTIti-ZU-unsplash.jpg'},
  {'url':'https://i.postimg.cc/wMbsbpnn/paulina-milde-jachowska-f-NW3-Mix6-F2-Y-unsplash.jpg'},
  {'url':'https://i.postimg.cc/QCBnzXHT/pawel-czerwinski-e-Ehwv-Ss3r1g-unsplash.jpg'},
  {'url':'https://i.postimg.cc/Kzt2Hrwb/pexels-anjana-c-674010.jpg'},
  {'url':'https://i.postimg.cc/8PmnnnCw/pexels-ann-h-1762851.jpg'},
  {'url':'https://i.postimg.cc/mDSHGMFx/pexels-anni-roenkae-2832382.jpg'},
  {'url':'https://i.postimg.cc/Sxjjt3rp/pexels-athena-1858409.jpg'},
  {'url':'https://i.postimg.cc/RZxcrMWz/pexels-cottonbro-studio-9665356.jpg'},
  {'url':'https://i.postimg.cc/RVDDwJpL/pexels-cottonbro-studio-9667079.jpg'},
  {'url':'https://i.postimg.cc/cCbGK98Q/pexels-cottonbro-studio-9667972.jpg'},
  {'url':'https://i.postimg.cc/SQ7ryYpx/pexels-cottonbro-studio-9695148.jpg'},
  {'url':'https://i.postimg.cc/x1rFsJMG/pexels-dan-gold-1660193.jpg'},
  {'url':'https://i.postimg.cc/dQhz0K9f/pexels-eriks-abzinovs-3117225.jpg'},
  {'url':'https://i.postimg.cc/RhBNsTC5/pexels-james-lee-2625664.jpg'},
  {'url':'https://i.postimg.cc/xTpF2NKb/pexels-louys-701855.jpg'},
  {'url':'https://i.postimg.cc/TYcWsBWk/pexels-madison-inouye-2821756.jpg'},
  {'url':'https://i.postimg.cc/fTSrjjtT/pexels-marina-leonova-7718572.jpg'},
  {'url':'https://i.postimg.cc/fTg0ZmBX/pexels-marina-leonova-7718577.jpg'},
  {'url':'https://i.postimg.cc/3N0WxbLv/pexels-pavlo-825995.jpg'},
  {'url':'https://i.postimg.cc/rwwXGtkh/pexels-wendel-moretti-1937738.jpg'},
  {'url':'https://i.postimg.cc/Wp5QN1rg/sam-mgrdichian-g-Jm-Pq5o-Lfg-unsplash.jpg'},
  {'url':'https://i.postimg.cc/Hk8GP1r5/solen-feyissa-d-PX8-Jb-Oxhf-A-unsplash.jpg'},
  {'url':'https://i.postimg.cc/cLyTZpDf/solen-feyissa-IRz-RDxx-Sbt4-unsplash.jpg'},
  {'url':'https://i.postimg.cc/qBFjDhyb/the-blowup-d8w-Qv6-Vo-Zjc-unsplash.jpg'},
]
const waterScreenData = [
  {'url':'https://i.postimg.cc/8PwhpZTy/7600d672-7d91-4f96-bf34-339dddda8c9a.png'},
  {'url':'https://i.postimg.cc/xCrmx7Pd/aachal-6ge-VJe-ZJMg8-unsplash.jpg'},
  {'url':'https://i.postimg.cc/qv5ynghy/arushee-agrawal-p-U0a4v-YJwco-unsplash.jpg'},
  {'url':'https://i.postimg.cc/nz74nZL7/colin-lloyd-Glibene-L-t-Y-unsplash.jpg'},
  {'url':'https://i.postimg.cc/MGg0kXzq/colin-lloyd-Jt-QFf-FLKa-E-unsplash.jpg'},
  {'url':'https://i.postimg.cc/fWccFwpQ/david-clode-f-G1fdervp1-E-unsplash.jpg'},
  {'url':'https://i.postimg.cc/hj9dHrC1/demian-tejeda-benitez-nc-Dn-KR-xh-Ag-unsplash.jpg'},
  {'url':'https://i.postimg.cc/BQCC8qBB/fabian-jones-Gt1-Ys4-O3-ML4-unsplash.jpg'},
  {'url':'https://i.postimg.cc/wM1d1WSh/ganapathy-kumar-5fhcbk-OPhw-A-unsplash.jpg'},
  {'url':'https://i.postimg.cc/yNnqv4Km/gissur-steinarsson-s-Zjh9-Mr-lg-unsplash.jpg'},
  {'url':'https://i.postimg.cc/j24yJXPS/guille-pozzi-PO0-UHx-5m-Ho-unsplash.jpg'},
  {'url':'https://i.postimg.cc/B6cjhv6h/ivan-bandura-1-Hp-6-Ank-Wkc-unsplash.jpg'},
  {'url':'https://i.postimg.cc/4yfmjTHX/ivan-bandura-5cwig-Xm-GWTo-unsplash.jpg'},
  {'url':'https://i.postimg.cc/qBFTPT3Q/jessica-furtney-zhq-D0tw1pe-A-unsplash.jpg'},
  {'url':'https://i.postimg.cc/X7yb3zKW/karl-fredrickson-x-FVazdd9o-Eg-unsplash.jpg'},
  {'url':'https://i.postimg.cc/44j3ztBJ/klara-kulikova-l-ILzdea-HJFA-unsplash.jpg'},
  {'url':'https://i.postimg.cc/L6rm1p4h/kyaw-tun-n-I3b-UW1-Xqik-unsplash.jpg'},
  {'url':'https://i.postimg.cc/yNh6KbHx/kyaw-tun-tp5sz33n-Bcg-unsplash.jpg'},
  {'url':'https://i.postimg.cc/Bnm9Cf4x/marcelo-quinan-upyw-S5-QFwr8-unsplash.jpg'},
  {'url':'https://i.postimg.cc/hj3kRLfh/masaaki-komori-Lu9z9q-S8-I-Q-unsplash.jpg'},
  {'url':'https://i.postimg.cc/L5cGnmkp/mathilda-khoo-J-REyy-XY14s-unsplash.jpg'},
  {'url':'https://i.postimg.cc/0yPPfCmq/naja-bertolt-jensen-50sl-SIOqy-ZA-unsplash.jpg'},
  {'url':'https://i.postimg.cc/6Q1KBJP9/naja-bertolt-jensen-Uu1-Ct-Kng-EXY-unsplash.jpg'},
  {'url':'https://i.postimg.cc/KY7TWfpr/nathan-dumlao-ci-O5-L8pin8-A-unsplash.jpg'},
  {'url':'https://i.postimg.cc/T1LZdKD0/octavian-rosca-e3-OSaoc7-Eu-E-unsplash.jpg'},
  {'url':'https://i.postimg.cc/KzLHw6Sp/pascal-van-de-vendel-CNd-MGa-VEoz-Q-unsplash.jpg'},
  {'url':'https://i.postimg.cc/25jjzx8x/pexels-artem-mizyuk-1739808.jpg'},
  {'url':'https://i.postimg.cc/ZYNmzQxS/pexels-elianne-dipp-4666751.jpg'},
  {'url':'https://i.postimg.cc/C13VfCYX/pexels-francesco-ungaro-3645203.jpg'},
  {'url':'https://i.postimg.cc/cHgSHkqf/pexels-francesco-ungaro-3723505.jpg'},
  {'url':'https://i.postimg.cc/5ydZtxSM/pexels-javon-swaby-1697620.jpg'},
  {'url':'https://i.postimg.cc/rsMQbz9z/pexels-leonid-danilov-2690766.jpg'},
  {'url':'https://i.postimg.cc/prJ1XKdD/pexels-neha-pandey-2446439.jpg'},
  {'url':'https://i.postimg.cc/SNmv11ZV/pexels-oliver-sj-str-m-1276531.jpg'},
  {'url':'https://i.postimg.cc/J0zjZXq3/pexels-pia-3046638.jpg'},
  {'url':'https://i.postimg.cc/L8bQX9m0/pexels-pixabay-67826.jpg'},
  {'url':'https://i.postimg.cc/vmxqxJB8/pexels-pixabay-68767.jpg'},
  {'url':'https://i.postimg.cc/j5KHqmnF/pexels-scott-webb-137613.jpg'},
  {'url':'https://i.postimg.cc/50M3YjTp/silas-baisch-f4bfv-VXKZP8-unsplash.jpg'},
 
]
app.get('/', (req, res) => {
  res.status(200).json(architectureScreenData);
});

app.listen(PORT, () => console.log('It\'s alive'));
